name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes da Controller
        run: npm run test-controller

      - name: Subir a API
        run: npm start &

      - name: Esperar a API estar funcionando
        run: sleep 5
      
      - name: Rodar os testes External
        run: nom run test-external
